#!/bin/bash

## Copyright (C) 2016 - 2017 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -e

counter=0

while true ; do
   for icon in success busy error ; do
      python3 -c "
icon = bytes(\"$icon\", encoding = 'utf-8')
with open(\"/var/run/sdwdate/status\", 'wb') as f:
      f.write(icon)
      f.close()"

      #msg="$(cat /proc/sys/kernel/random/uuid)"
      echo "$icon" > /var/run/sdwdate/msg

      counter=$(( counter + 1 ))
      if [ "$counter" -ge 10000 ]; then
         do_break=true
      fi

      #sleep 1
   done
   if [ "$do_break" = "true" ]; then
      break
   fi
done
