.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "SDWDATE\-GUI" "1" "January 2020" "sdwdate-gui" "sdwdate-gui Manual"
.SH "NAME"
\fBsdwdate\-gui\fR \- monitor and user interface for sdwdate
.SH "SYNOPSIS"
\fBsdwdate\-gui\fR
.SH "DESCRIPTION"
Monitor and user interface for sdwdate\.
.SH "WWW"
https://www\.whonix\.org/wiki/sdwdate\-gui
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
