#!/bin/bash

## Copyright (C) 2018 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

set -e

## Use '--boot' to avoid confusion from showing previous boot inside Qubes TemplateVM.

/usr/lib/helper-scripts/terminal-wrapper "sudo --non-interactive /bin/journalctl --boot --output cat -n 10000 -f _SYSTEMD_UNIT=sdwdate.service + _SYSTEMD_UNIT=whonix-firewall.service + SYSLOG_IDENTIFIER=suspend-pre + SYSLOG_IDENTIFIER=suspend-post"
