#!/bin/bash

## Copyright (C) 2018 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions

set -x

NAME="$(/usr/bin/qubesdb-read /name)"

if [ ! -z "$NAME" ]; then
    /usr/bin/qrexec-client-vm sys-whonix whonix.NewStatus+$NAME" shutdown"
    true
fi
