#!/usr/bin/python3 -u

## Copyright (C) 2015 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from sdwdate_gui import sdwdate_gui
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

sdwdate_gui.main()
