#!/usr/bin/env python

import sys
import signal
from PyQt4 import QtGui
from PyQt4 import QtCore
from PyQt4.QtCore import Qt


class TitleBar(QtGui.QDialog):
    def __init__(self, parent=None):
        QtGui.QWidget.__init__(self, parent)
        self.setWindowFlags(Qt.FramelessWindowHint)
        self.setStyle(QtGui.QStyleFactory.create('CleanLooks'))
        css = """
            QWidget
            {
            Background:lightyellow;
            color:black;
            font:12px bold;
            font-weight:bold;
            border-radius: 5px;
            height: 11px;
            }
            QToolButton
            {
            Background:lightyellow;
            }
            QToolButton:hover
            {
            font:12px
            Background:yellow;
            }
            """
        self.setStyleSheet(css)

        close=QtGui.QToolButton(self);
        close.setIcon(QtGui.QIcon('/usr/share/icons/sdwdate-gui/button_cancel.png'))
        close.clicked.connect(self.close);

        title = QtGui.QLabel(self);
        title.setText("Time Synchronisation Monitor    ");

        title_layout = QtGui.QHBoxLayout(self);
        title_layout.addWidget(title);
        title_layout.addWidget(close);

    def close(self):
        popup.close()


class Frame(QtGui.QFrame):
    def __init__(self, parent=None):
        QtGui.QFrame.__init__(self, parent)
        css = """
            QFrame
            {
            Background:lightyellow;
            color:black;
            font:12px ;
            border-radius: 5px;
            }
            """
        self.setStyleSheet(css)
        self.setWindowFlags(Qt.FramelessWindowHint);
        self.m_content= QtGui.QWidget(self);
        self.m_titleBar= TitleBar(self);

        frame_layout = QtGui.QVBoxLayout(self);
        frame_layout.addWidget(self.m_titleBar);
        frame_layout.addWidget(self.m_content);
        frame_layout.setMargin(5);

    # Allows you to access the content area of the frame
    # where widgets and layouts can be added
    def contentWidget(self):
        return self.m_content

def signal_handler(*args):
    QtGui.QApplication.exit()

if __name__ == '__main__':
    signal.signal(signal.SIGINT, signal_handler)

    app = QtGui.QApplication(sys.argv);
    msg = sys.argv[1]
    pos_x = int(sys.argv[2])
    pos_y = int(sys.argv[3])

    popup = Frame()
    content = QtGui.QVBoxLayout(popup.contentWidget());

    text = QtGui.QLabel()
    text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse |
                                 QtCore.Qt.TextSelectableByMouse)
    text.setText(msg)
    content.addWidget(text)

    popup.move(pos_x, pos_y);
    popup.show()

    ## Python cannot handle signals while the Qt event loop is running.
    ## The signal handler is called when a Python function is called
    timer = QtCore.QTimer()
    timer.start(10)
    timer.timeout.connect(lambda: None)

    sys.exit(app.exec_())
