#!/bin/bash

## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

if [ -e /var/run/qubes/this-is-templatevm ]; then
   exit 0
fi

if [ -d /usr/lib/qubes ]; then
   ## Do not automatically start sdwdate-gui in Qubes due to various issues.
   ## - https://github.com/QubesOS/qubes-issues/issues/2264
   ## - https://github.com/QubesOS/qubes-issues/issues/2268
   ## - https://phabricator.whonix.org/T534
   exit 0
fi

sdwdate-gui
