#!/bin/bash

## Copyright (C) 2012 - 2014 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

if [ -d /usr/lib/qubes ]; then
    VM_TYPE="$(/usr/bin/qubesdb-read /qubes-vm-type)"

    if [ "$VM_TYPE" == "AppVM" ]; then
        /usr/lib/sdwdate-gui/sdwdate-watcher
        true
    elif [ "$VM_TYPE"  == "ProxyVM" ]; then
        sdwdate-gui-qubes
        true
    fi

else
    sdwdate-gui
fi
