#!/bin/bash

## Copyright (C) 2018 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x

set -e

terminal_emulator_window_title="sdwdate Log Viewer"
export terminal_emulator_window_title

/usr/libexec/helper-scripts/terminal-wrapper "leaprun sdwdate-log-viewer"
