#!/bin/bash

## Copyright (C) 2018 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x

set -e

/usr/libexec/helper-scripts/terminal-wrapper "sudo --non-interactive /usr/bin/sdwdate-log-viewer"
