#!/bin/bash

## Copyright (C) 2018 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions

set -x

shopt -s nullglob
for i in \
   /etc/sdwdate-gui.d/*.conf \
   /usr/local/etc/sdwdate-gui.d/*.conf \
   ; do
      bash -n "$i"
      source "$i"
done

if ! test -f /usr/share/qubes/marker-vm ; then
   true "$0: INFO: Not implemented for Non-Qubes. Exiting. Ok."
   exit 0
fi

## https://forums.whonix.org/t/qubes-os-4-1-denied-whonix-newstatus-dom0-permission/12954
if test -e /usr/share/anon-gw-base-files/gateway ; then
   true "$0: INFO: Gateway detected. No need to notify self. Exiting. Ok."
   exit 0
fi

if [ "$disable" = "true" ]; then
   exit 0
fi

## If gateway is not configured in config file, use default.
if [ "$gateway" = "" ]; then
   gateway=sys-whonix
fi

name_of_this_vm="$(qubesdb-read /name)"

if [ "$name_of_this_vm" = "" ]; then
   true "$0: NOTICE: name_of_this_vm is empty. Cannot notify that this machine is shutdown."
   exit 0
fi

/usr/bin/qrexec-client-vm "$gateway" "whonix.NewStatus+$name_of_this_vm shutdown"

true
