#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

socket_check_counter=0

server_enabled="$(/usr/libexec/sdwdate-gui/sdwdate-gui-config-read 'run_server_in_qubes')" || exit 1

if [ "${server_enabled}" != 'true' ]; then
  touch /run/sdwdate-gui-qubes-should-proxy
else
  while (( socket_check_counter < 20 )); do
    sleep 1
    (( socket_check_counter += 1 )) || true
    if [ -S '/run/user/1000/sdwdate-gui/sdwdate-gui-server.socket' ]; then
      ln -s '/run/user/1000/sdwdate-gui/sdwdate-gui-server.socket' \
        '/run/qubes-rpc/sdwdate.Connect'
      break
    fi
  done
fi
