#!/usr/bin/python3 -u

## Copyright (C) 2015 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

from sdwdate_gui import sdwdate_watcher
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

sdwdate_watcher.main()
