#!/usr/bin/python3 -su

## Copyright (C) 2015 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

from sdwdate_gui import sdwdate_gui
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

sdwdate_gui.main()
