#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#set -x
set -e

socket_check_counter=0

server_enabled="$(/usr/libexec/sdwdate-gui/sdwdate-gui-config-read 'run_server_in_qubes')" || exit 1

if [ "${server_enabled}" != 'true' ]; then
  touch /run/sdwdate-gui-qubes-should-proxy
else
  while (( socket_check_counter < 20 )); do
    sleep 1
    (( socket_check_counter += 1 )) || true
    ## XXX: Hardcoded. uid 1000 is hardcoded.
    ## BUG: When sys-whonix is booted in sysmaint session, uid is not 1000.
    ##      It is 1001 but that may not be guaranteed.
    true "INFO: $0: Check if /run/user/1000/sdwdate-gui/sdwdate-gui-server.socket socket file already exists..."
    if [ -S '/run/user/1000/sdwdate-gui/sdwdate-gui-server.socket' ]; then
      true "INFO: $0: socket file exists: yes"
      ln -s '/run/user/1000/sdwdate-gui/sdwdate-gui-server.socket' '/run/qubes-rpc/sdwdate-gui.Connect'
      break
    fi
    true "INFO: $0: socket file exists: no"
  done
fi
