#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

shopt -s nullglob
for i in \
   /etc/sdwdate-gui.d/*.conf \
   /usr/local/etc/sdwdate-gui.d/*.conf \
   ; do
      bash -n "$i"
      source "$i"
done

if test -f /run/qubes-service/no-sdwdate ; then
   true "INFO: /run/qubes-service/no-sdwdate exists, exiting, ok."
   exit 0
fi

if [ "$disable" = "true" ]; then
   exit 0
fi

if [ -d /usr/lib/qubes ]; then
    VM_TYPE="$(/usr/bin/qubesdb-read /qubes-vm-type)"

    if [ "$VM_TYPE" == "AppVM" ]; then
        /usr/libexec/sdwdate-gui/sdwdate-watcher
        true
    elif [ "$VM_TYPE"  == "ProxyVM" ]; then
        sdwdate-gui-qubes
        true
    fi

else
    sdwdate-gui
fi
